### ISSUE TITLE
[Task] writing & updating 시 이미지 S3버킷 생성 & 클라이언트 배포환경 재세팅/ 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/pick-me-up#148]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: DB나 서버에서 이미지 파일 저장하고 다루기 까다로움. 
따라서 AWS S3 버킷을 활용하여 서버리스 이미지 저장소 만들어보기

**TODO**
1. [ ] aws s3 버킷 생성하기
2. [ ] 클라이언트에서 파일 업로드시 URL 생성 코드 작성
3. [ ] URL 바로 <img>에 띄워보기

**Estimated time**
> Pick one
```2h```

**Labels**
- Estimated time: ```E: 2h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__```
- Urgency: ```High```
