### ISSUE TITLE
[Task] voting 관련 API 요청 및 응답데이터 랜더링 구현 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/pick-me-up#149]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: voting 관련 API 요청 3가지 및 응답데이터 랜더링 구현 

**TODO**
1. [ ] 피드 투표하기 클릭하였을 때 이미 투표한 유저인지 아닌지 판단하는 GET 요청
2. [ ] 투표 안 한 사람이 최초 투표할 때 투표수+1 되는 POST 요청
3. [ ] 투표완료 직후 업데이트 된 투표수를 응답받는 POST요청

**Estimated time**
> Pick one
```4h```

**Labels**
- Estimated time: ```E: 4h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__2```
- Urgency: ```High```
