### ISSUE TITLE
[Task] 투표 시 유저flow 내 버그(결과페이지 랜더링 조건별로 안 띄워짐 & 데이터 업뎃 안 됨) 수정 / 박지영 

### ISSUE THREAD

**Issue by devLuenna** [codestates/pick-me-up#151]
**ISSUE**
- Group: ```client```
- Type: ```bug```
- Detail: 투표 시 유저 flow 내 버그 수정

**TODO**
1. [ ] 투표하였을 때 바로 결과값 반영 안 됨. 수정하기
2. [ ] 투표하였을 때 이미 투표한 사람이면 결과값에서 텍스트 메세지 띄우기
3. [ ] 비로그인자가 투표하였을 때 로그인이 필요합니다 메세지 띄우기

**Estimated time**
> Pick one
```2h```

**Labels**
- Estimated time: ```E: 2h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__```
- Urgency: ```High```
