### ISSUE TITLE
[Task] DB user Table 수정 및 회원가입 로직 구현

### ISSUE THREAD

**Issue by dongukuklee** [codestates/pick-me-up#19]
**ISSUE**
- Group: ```server```
- Type: ```feature```
- Detail:  DB user Table 수정 및 회원가입 로직 구현

**TODO**
1. [ ] DB user Table 수정
2. [ ] 회원가입 로직 구현
3. [ ] 회원가입 유효성 검사
