### ISSUE TITLE
[Task] 스크롤해도 상단 네비게이션바 및 해시태그 카테고리 고정 

### ISSUE THREAD

**Issue by devLuenna** [codestates/pick-me-up#80]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: 스크롤 했을 때 상단에 navbar 와 해시태그 카테고리 고정시키기.

**TODO**
1. [ ] 스크롤 했을 때 상단에 navbar 고정시키기. 
2. [ ] 해시태그 카테고리 고정시키기.
3. [ ] navbar 스크롤 시 색깔 변경
4. [ ] 마이페이지에서도 subnavbar 고정

**Estimated time**
> Pick one
```2h```

**Labels**
- Estimated time: ```E: 2h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__```
- Urgency: ``` Low```
